//Execute fight on Subscriber

POST http://localhost:7001/subscribe/fight
Content-Type: application/json

{ "BotName": "Name", "BotCode": "Bot code" }

###

//Publish message to a topic

POST http://localhost:7000/publish
Content-Type: application/json

{ "BotName": "Published", "BotCode": "Bot code2" }

###
